package com.example.utilizador.pirloit;


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import com.j256.ormlite.field.DatabaseField;

public class Evento {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField(index = true)
    String modalidade;
    @DatabaseField
    String local;
    @DatabaseField
    Date date;

    Evento() {
        // needed by ormlite
    }

    public Evento(String modalidade, String local, long millis) {
        this.date = new Date(millis);
        this.modalidade = modalidade;
        this.local = local;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(id);
        sb.append(", ").append("str=").append(modalidade);
        sb.append(", ").append("loc=").append(local);
        SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd HH:mm:ss", Locale.US);
        sb.append(", ").append("date=").append(dateFormatter.format(date));
        return sb.toString();
    }
}